FROM ubuntu:22.04

# Install necessary packages
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update \
    && apt-get install -y wget bzip2 make unzip cppcheck

# Create a non-root user named "ubuntu"
RUN useradd -rm -d /home/ubuntu -s /in/bash -g root -G sudo \
    -u 1001 ubuntu
USER ubuntu
WORKDIR /home/ubuntu
