on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: mattgpaul/atmega328p:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - run: TOOLS_PATH=/home/ubuntu/dev/tools make
      - run: make cppcheck